[package]
name = "my_microservice"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
env_logger = "0.10"
mime = "0.3.17"
derive_more = "2.0.1"
